import type { Student } from './common/student';

// Mock 学生数据
export const mockStudents: Student[] = [
  {
    studentId: 'S2023001',
    name: '张三',
    gender: '男',
    age: 15,
    birthDate: '2008-03-15',
    className: '初一(1)班',
    enrollmentYear: 2023,
    phone: '13800138000',
    address: '北京市海淀区XX路XX号',
    isBoarding: true,
    dormitory: '3号楼402室',
    hobbies: ['篮球', '编程'],
    customHobbies: ['阅读'],
    specialty: '计算机编程',
    guardianName: '张大山',
    guardianRelation: '父亲',
    guardianPhone: '13900139000',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 85 },
          { subject: '数学', score: 92 },
          { subject: '英语', score: 78 },
        ],
      },{
        period: 2,
        subjects: [
          { subject: '语文', score: 84 },
          { subject: '数学', score: 91 },
          { subject: '英语', score: 77 },
        ],
      },
    ],
  },
  {
    studentId: 'S2023002',
    name: '李四',
    gender: '女',
    age: 14,
    birthDate: '2009-05-20',
    className: '初一(1)班',
    enrollmentYear: 2023,
    phone: '13800138001',
    address: '北京市朝阳区XX路XX号',
    isBoarding: false,
    hobbies: ['音乐', '绘画'],
    specialty: '钢琴演奏',
    guardianName: '李小红',
    guardianRelation: '母亲',
    guardianPhone: '13900139001',
    scores: [
      {
        period: 2,
        subjects: [
          { subject: '语文', score: 88 },
          { subject: '数学', score: 90 },
          { subject: '英语', score: 95 },
        ],
      },
    ],
  },
  {
    studentId: 'S2023003',
    name: '王五',
    gender: '男',
    age: 16,
    birthDate: '2007-08-12',
    className: '初一(2)班',
    enrollmentYear: 2023,
    phone: '13800138002',
    address: '北京市西城区XX路XX号',
    isBoarding: true,
    dormitory: '2号楼305室',
    hobbies: ['足球', '阅读'],
    customHobbies: ['游泳'],
    specialty: '足球',
    guardianName: '王强',
    guardianRelation: '父亲',
    guardianPhone: '13900139002',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 75 },
          { subject: '数学', score: 88 },
          { subject: '英语', score: 82 },
        ],
      },
    ],
  },
  {
    studentId: 'S2023004',
    name: '赵六',
    gender: '女',
    age: 15,
    birthDate: '2008-11-25',
    className: '初一(2)班',
    enrollmentYear: 2023,
    phone: '13800138003',
    address: '北京市东城区XX路XX号',
    isBoarding: false,
    hobbies: ['舞蹈', '音乐'],
    specialty: '民族舞',
    guardianName: '赵明',
    guardianRelation: '父亲',
    guardianPhone: '13900139003',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 92 },
          { subject: '数学', score: 85 },
          { subject: '英语', score: 90 },
        ],
      },
    ],
  },
  {
    studentId: 'S2023005',
    name: '孙七',
    gender: '男',
    age: 14,
    birthDate: '2009-02-18',
    className: '初一(3)班',
    enrollmentYear: 2023,
    phone: '13800138004',
    address: '北京市丰台区XX路XX号',
    isBoarding: true,
    dormitory: '1号楼201室',
    hobbies: ['编程', '阅读'],
    customHobbies: ['数学'],
    specialty: '信息学竞赛',
    guardianName: '孙丽',
    guardianRelation: '母亲',
    guardianPhone: '13900139004',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 80 },
          { subject: '数学', score: 95 },
          { subject: '英语', score: 88 },
        ],
      },
    ],
  },
  {
    studentId: 'S2023006',
    name: '周八',
    gender: '女',
    age: 15,
    birthDate: '2008-07-30',
    className: '初一(3)班',
    enrollmentYear: 2023,
    phone: '13800138005',
    address: '北京市石景山区XX路XX号',
    isBoarding: false,
    hobbies: ['绘画', '阅读'],
    specialty: '国画',
    guardianName: '周华',
    guardianRelation: '父亲',
    guardianPhone: '13900139005',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 90 },
          { subject: '数学', score: 82 },
          { subject: '英语', score: 85 },
        ],
      },
    ],
  },
  {
    studentId: 'S2022001',
    name: '吴九',
    gender: '男',
    age: 16,
    birthDate: '2007-04-10',
    className: '初二(1)班',
    enrollmentYear: 2022,
    phone: '13800138006',
    address: '北京市海淀区XX路XX号',
    isBoarding: true,
    dormitory: '3号楼501室',
    hobbies: ['篮球', '足球'],
    specialty: '篮球',
    guardianName: '吴军',
    guardianRelation: '父亲',
    guardianPhone: '13900139006',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 78 },
          { subject: '数学', score: 85 },
          { subject: '英语', score: 80 },
        ],
      },
    ],
  },
  {
    studentId: 'S2022002',
    name: '郑十',
    gender: '女',
    age: 15,
    birthDate: '2008-09-15',
    className: '初二(1)班',
    enrollmentYear: 2022,
    phone: '13800138007',
    address: '北京市朝阳区XX路XX号',
    isBoarding: false,
    hobbies: ['音乐', '舞蹈'],
    customHobbies: ['声乐'],
    specialty: '声乐',
    guardianName: '郑芳',
    guardianRelation: '母亲',
    guardianPhone: '13900139007',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 88 },
          { subject: '数学', score: 90 },
          { subject: '英语', score: 92 },
        ],
      },
    ],
  },
  {
    studentId: 'S2022003',
    name: '钱十一',
    gender: '男',
    age: 16,
    birthDate: '2007-12-05',
    className: '初二(2)班',
    enrollmentYear: 2022,
    phone: '13800138008',
    address: '北京市西城区XX路XX号',
    isBoarding: true,
    dormitory: '2号楼410室',
    hobbies: ['编程', '阅读'],
    customHobbies: ['电子制作'],
    specialty: '机器人编程',
    guardianName: '钱伟',
    guardianRelation: '父亲',
    guardianPhone: '13900139008',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 82 },
          { subject: '数学', score: 92 },
          { subject: '英语', score: 85 },
        ],
      },
    ],
  },
  {
    studentId: 'S2022004',
    name: '冯十二',
    gender: '女',
    age: 15,
    birthDate: '2008-01-22',
    className: '初二(2)班',
    enrollmentYear: 2022,
    phone: '13800138009',
    address: '北京市东城区XX路XX号',
    isBoarding: false,
    hobbies: ['绘画', '阅读'],
    specialty: '素描',
    guardianName: '冯静',
    guardianRelation: '母亲',
    guardianPhone: '13900139009',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 85 },
          { subject: '数学', score: 88 },
          { subject: '英语', score: 90 },
        ],
      },
    ],
  },
  {
    studentId: 'S2022005',
    name: '陈十三',
    gender: '男',
    age: 16,
    birthDate: '2007-06-18',
    className: '初二(2)班',
    enrollmentYear: 2022,
    phone: '13800138010',
    address: '北京市丰台区XX路XX号',
    isBoarding: true,
    dormitory: '1号楼302室',
    hobbies: ['足球', '篮球'],
    specialty: '足球',
    guardianName: '陈刚',
    guardianRelation: '父亲',
    guardianPhone: '13900139010',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 75 },
          { subject: '数学', score: 80 },
          { subject: '英语', score: 78 },
        ],
      },
    ],
  },
  {
    studentId: 'S2021001',
    name: '楚十四',
    gender: '女',
    age: 17,
    birthDate: '2006-03-28',
    className: '初三(1)班',
    enrollmentYear: 2021,
    phone: '13800138011',
    address: '北京市石景山区XX路XX号',
    isBoarding: false,
    hobbies: ['音乐', '阅读'],
    customHobbies: ['小提琴'],
    specialty: '小提琴演奏',
    guardianName: '楚梅',
    guardianRelation: '母亲',
    guardianPhone: '13900139011',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 90 },
          { subject: '数学', score: 88 },
          { subject: '英语', score: 95 },
        ],
      },
    ],
  },
  {
    studentId: 'S2021002',
    name: '卫十五',
    gender: '男',
    age: 17,
    birthDate: '2006-08-14',
    className: '初三(1)班',
    enrollmentYear: 2021,
    phone: '13800138012',
    address: '北京市海淀区XX路XX号',
    isBoarding: true,
    dormitory: '3号楼601室',
    hobbies: ['编程', '阅读'],
    customHobbies: ['算法'],
    specialty: '算法竞赛',
    guardianName: '卫国',
    guardianRelation: '父亲',
    guardianPhone: '13900139012',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 85 },
          { subject: '数学', score: 98 },
          { subject: '英语', score: 88 },
        ],
      },
    ],
  },
  {
    studentId: 'S2023007',
    name: '蒋十六',
    gender: '女',
    age: 14,
    birthDate: '2009-10-08',
    className: '初一(1)班',
    enrollmentYear: 2023,
    phone: '13800138013',
    address: '北京市朝阳区XX路XX号',
    isBoarding: false,
    hobbies: ['舞蹈', '绘画'],
    specialty: '现代舞',
    guardianName: '蒋丽',
    guardianRelation: '母亲',
    guardianPhone: '13900139013',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 88 },
          { subject: '数学', score: 85 },
          { subject: '英语', score: 90 },
        ],
      },
    ],
  },
  {
    studentId: 'S2023008',
    name: '沈十七',
    gender: '男',
    age: 15,
    birthDate: '2008-12-20',
    className: '初一(2)班',
    enrollmentYear: 2023,
    phone: '13800138014',
    address: '北京市西城区XX路XX号',
    isBoarding: true,
    dormitory: '2号楼206室',
    hobbies: ['篮球', '编程'],
    customHobbies: ['游戏开发'],
    specialty: '游戏开发',
    guardianName: '沈强',
    guardianRelation: '父亲',
    guardianPhone: '13900139014',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 80 },
          { subject: '数学', score: 90 },
          { subject: '英语', score: 85 },
        ],
      },
    ],
  },
  {
    studentId: 'S2023009',
    name: '韩十八',
    gender: '女',
    age: 14,
    birthDate: '2009-06-03',
    className: '初一(3)班',
    enrollmentYear: 2023,
    phone: '13800138015',
    address: '北京市东城区XX路XX号',
    isBoarding: false,
    hobbies: ['音乐', '阅读'],
    specialty: '古筝',
    guardianName: '韩芳',
    guardianRelation: '母亲',
    guardianPhone: '13900139015',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 92 },
          { subject: '数学', score: 88 },
          { subject: '英语', score: 93 },
        ],
      },
    ],
  },
  {
    studentId: 'S2023010',
    name: '杨十九',
    gender: '男',
    age: 16,
    birthDate: '2007-09-25',
    className: '初一(1)班',
    enrollmentYear: 2023,
    phone: '13800138016',
    address: '北京市丰台区XX路XX号',
    isBoarding: true,
    dormitory: '1号楼401室',
    hobbies: ['足球', '阅读'],
    customHobbies: ['物理'],
    specialty: '物理竞赛',
    guardianName: '杨明',
    guardianRelation: '父亲',
    guardianPhone: '13900139016',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 82 },
          { subject: '数学', score: 95 },
          { subject: '英语', score: 88 },
        ],
      },
    ],
  },
  {
    studentId: 'S2022010',
    name: '朱二十',
    gender: '女',
    age: 15,
    birthDate: '2008-04-17',
    className: '初二(1)班',
    enrollmentYear: 2022,
    phone: '13800138017',
    address: '北京市石景山区XX路XX号',
    isBoarding: false,
    hobbies: ['绘画', '音乐'],
    customHobbies: ['水彩'],
    specialty: '水彩画',
    guardianName: '朱静',
    guardianRelation: '母亲',
    guardianPhone: '13900139017',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 90 },
          { subject: '数学', score: 85 },
          { subject: '英语', score: 92 },
        ],
      },
    ],
  },
  {
    studentId: 'S2021003',
    name: '秦二十一',
    gender: '男',
    age: 17,
    birthDate: '2006-11-30',
    className: '初三(1)班',
    enrollmentYear: 2021,
    phone: '13800138018',
    address: '北京市海淀区XX路XX号',
    isBoarding: true,
    dormitory: '3号楼702室',
    hobbies: ['篮球', '编程'],
    customHobbies: ['人工智能'],
    specialty: '人工智能',
    guardianName: '秦军',
    guardianRelation: '父亲',
    guardianPhone: '13900139018',
    scores: [
      {
        period: 1,
        subjects: [
          { subject: '语文', score: 88 },
          { subject: '数学', score: 96 },
          { subject: '英语', score: 90 },
        ],
      },
    ],
  },
];

// 性别选项
export const mockGenderOptions = [
  { label: '男', value: '男' },
  { label: '女', value: '女' }
]

// 班级选项
export const mockClassOptions = [
  { label: '初一(1)班', value: '初一(1)班' },
  { label: '初一(2)班', value: '初一(2)班' },
  { label: '初一(3)班', value: '初一(3)班' },
  { label: '初二(1)班', value: '初二(1)班' },
  { label: '初二(2)班', value: '初二(2)班' },
  { label: '初三(1)班', value: '初三(1)班' },
];

// 入学年份选项
export const mockEnrollmentYearOptions = [
  { label: '2021', value: 2021 },
  { label: '2022', value: 2022 },
  { label: '2023', value: 2023 },
];

// 兴趣爱好选项
export const mockHobbyOptions = [
  { label: '篮球', value: '篮球' },
  { label: '足球', value: '足球' },
  { label: '音乐', value: '音乐' },
  { label: '舞蹈', value: '舞蹈' },
  { label: '编程', value: '编程' },
  { label: '绘画', value: '绘画' },
  { label: '阅读', value: '阅读' },
];  